# Generated by Django 2.1.7 on 2019-04-08 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='电影名')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=20, verbose_name='职业')),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(verbose_name='年龄')),
                ('description', models.CharField(max_length=10, verbose_name='年龄区间')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(verbose_name='评分')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkprediction.Movie', verbose_name='电影')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=1, verbose_name='性别')),
                ('ageRange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkprediction.Range', verbose_name='年龄区间')),
                ('movies', models.ManyToManyField(through='linkprediction.Rating', to='linkprediction.Movie', verbose_name='看过的电影')),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkprediction.Occupation', verbose_name='职业')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkprediction.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkprediction.Tag', verbose_name='电影类别'),
        ),
    ]
