# Generated by Django 2.1.7 on 2019-04-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkprediction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
