# Generated by Django 2.1.7 on 2019-04-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkprediction', '0003_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=4, verbose_name='性别'),
        ),
    ]
