# Generated by Django 2.1.7 on 2019-04-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkprediction', '0006_auto_20190416_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='abstract',
            field=models.TextField(blank=True, default='这个电影没有简介~', null=True, verbose_name='简介'),
        ),
    ]
