# Generated by Django 2.1.7 on 2019-04-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkprediction', '0007_auto_20190417_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupation',
            options={'verbose_name': '职业'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签'},
        ),
    ]
