# Generated by Django 2.1.7 on 2019-04-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkprediction', '0009_auto_20190417_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'verbose_name': '职业', 'verbose_name_plural': '职业'},
        ),
        migrations.AlterModelOptions(
            name='range',
            options={'verbose_name': '年龄', 'verbose_name_plural': '年龄'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': '评分', 'verbose_name_plural': '评分'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
